#!/bin/bash

mkdir -p ~/bin

# Get rid of old blanc scripts if they exist.
rm -f ~/bin/blanc-add-git-hooks
rm -f ~/bin/blanc-createsuperuser
rm -f ~/bin/blanc-reset
rm -f ~/bin/blanc-clean-branches
rm -f ~/bin/blanc-dev-superuser
rm -f ~/bin/blanc-wipeenv

cp -f bin/* ~/bin

mkdir -p ~/.developersociety/git-hooks
cp --remove-destination  git-hooks/* ~/.developersociety/git-hooks
